print ()
print("Tell me YOUR SCORE in this semester")
FE = float(input("FE(25Point) : "))
GB = float(input("GB(25Point) : "))
ICS = float(input("ICS(25Point) : "))
CP = float(input("CP(25Point) : "))

print()
print("--- Your Total Score ---")
print (FE, "Points")
print (GB, "Points")
print (ICS, "Points")
print (CP, "Points")

print()
print("--- Your Total Score is!",FE+GB+ICS+CP,"/100 Points---")
